# backend/print_config.py

DPI = 300
PX_PER_CM = DPI / 2.54

SHEET_WIDTH_CM = 57
SHEET_HEIGHT_CM = 100
SPACING_CM = 0.02

SHEET_WIDTH_PX = int(SHEET_WIDTH_CM * PX_PER_CM)
SHEET_HEIGHT_PX = int(SHEET_HEIGHT_CM * PX_PER_CM)
SPACING_PX = int(SPACING_CM * PX_PER_CM)
